import exception

test.multiply(3,6)
test.multiply("3", "6")
